### ISSUE TITLE
Meetup 19-10-16

### ISSUE THREAD

**Issue by mfeckie** [elixir-perth/meetup#1]
Luke has offered to give us a talk about how awesome pattern matching is.

**Comment by lukerollans** [comment]
I figure the first few talks of our first meetups should touch on the core staples of the language, pattern matching being one of them.

It'll possibly consist of three primary sections.
1. Introduction to pattern matching and to establish how core it is to the language
2. Getting crazier with more advanced examples (possibly List tail recursion)
3. Closing up with a real world example, such as custom changeset functions which pattern match on changesets they should alter. Might also be a good chance to touch on Ecto basics.

Open to suggestions!

**Comment by mfeckie** [comment]
Marking this as done :)
